# Generated by Django 3.1.3 on 2020-12-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201205_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
